version: 2
jobs:
  create_builder:
    machine: true
    steps:
      - checkout
      - run:
          name: Check commit of generated content
          command: |
            set -v
            tag=$CIRCLE_TAG
            release_commit_msg="$(git log -1 --pretty=%B | head -n 1 || true)"
            if [ "$release_commit_msg" = ":gem: Release $tag" ]; then
              echo "This is a commit with generated content, skipping"
              circleci step halt
            fi
      - restore_cache:
          key: builder-{{ checksum ".builder/Dockerfile" }}
          paths:
              - /tmp/builder_pushed
      - run:
          name: Build and push image if builder/Dockerfile has changed
          command:  |

            if [ ! -f /tmp/docker_pushed ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              echo "Building $CI_PROJECT_PATH-builder:latest"
              docker pull "$CI_PROJECT_PATH-builder:latest" || true
              docker build -f .builder/Dockerfile -t "$CI_PROJECT_PATH-builder:latest" .
              docker push "$CI_PROJECT_PATH-builder:latest"
              echo 1 > /tmp/docker_pushed
            fi
      - save_cache:
          key: builder-{{ checksum ".builder/Dockerfile" }}
          paths:
              - /tmp/builder_pushed
  build:
    docker:
      - image: "$CI_PROJECT_PATH-builder:latest"
      
    working_directory: /go/src/github.com/MeneDev/dockmoor
    environment:
      - DEP_VERSION: 0.5.0
      - GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - run:
          name: Check commit of generated content
          command: |
            set -v
            tag=$CIRCLE_TAG
            release_commit_msg="$(git log -1 --pretty=%B | head -n 1 || true)"
            if [ "$release_commit_msg" = ":gem: Release $tag" ]; then
              echo "This is a commit with generated content, skipping"
              circleci step halt
            fi
      - restore_cache:
          key: gopkg-{{ checksum "Gopkg.lock" }}
          paths:
              - /go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/vendor
              - /tmp/go/cache
      - run:
          name: Download and build libraries
          command: |
            if [ ! -d ./vendor ]; then
                /go/bin/dep ensure
                find vendor/ -maxdepth 3 -mindepth 3 -exec bash -c 'cd $0 && go build  ./...' {} \;
            fi
      - save_cache:
          key: gopkg-{{ checksum "Gopkg.lock" }}
          paths:
              - ./vendor
              - /tmp/go/cache

#      - setup_remote_docker

      - run:
          name: Test
          command: |
            go test -v ./... -cover -race -coverprofile=/tmp/coverage.out
            $GOPATH/bin/goveralls -coverprofile=/tmp/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

      - run:
          name: Build project
          command: |
            set -v
            tag=$CIRCLE_TAG

            echo "Building Tag '$tag'"
            export tag
            find cmd/ -maxdepth 1 -mindepth 1 -exec bash -c 'cd $0 && gox -ldflags="-s -w -X \"main.Version=${tag}\" -X \"main.BuildDate=$(date --utc)\" -X \"main.BuildNumber=$CIRCLE_BUILD_NUM\" -X \"main.BuildCommit=$CIRCLE_SHA1\"" -os="linux windows darwin" -arch="amd64" -output "../../release/${0##*/}-{{.OS}}_{{.Arch}}"' {} \;
            release/dockmoor-linux_amd64 --version

      - persist_to_workspace:
          root: .
          paths:
            - release
  release:
    docker:
      - image: "$CI_PROJECT_PATH-builder:latest"
    working_directory: /go/src/github.com/MeneDev/dockmoor
    steps:
      - checkout
      - run:
          name: Check commit of generated content
          command: |
            set -v
            tag=$CIRCLE_TAG
            release_commit_msg="$(git log -1 --pretty=%B | head -n 1 || true)"
            if [ "$release_commit_msg" = ":gem: Release $tag" ]; then
              echo "This is a commit with generated content, skipping"
              circleci step halt
            fi
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Verify CHANGELOG contains release tag
          command: |
            if ! cat CHANGELOG.md | grep "## $tag" ; then
              echo "Missing Changelog entry for $tag, refusing to release"
              exit 1
            fi
      - restore_cache:
          key: gopkg-{{ checksum "Gopkg.lock" }}
          paths:
          - /go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/vendor
          - /tmp/go/cache
      - run:
          name: Download and build libraries
          command: |
            if [ ! -d ./vendor ]; then
                /go/bin/dep ensure
                find vendor/ -maxdepth 3 -mindepth 3 -exec bash -c 'cd $0 && go build  ./...' {} \;
            fi
      - save_cache:
          key: gopkg-{{ checksum "Gopkg.lock" }}
          paths:
          - ./vendor
          - /tmp/go/cache

      - run:
          name: End-to-End Test
          command: |
            cd cmd/dockmoor/end-to-end && ./test.sh

      - run:
          name: Update README.adoc
          command: |
            set -v
            tag=$CIRCLE_TAG

            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "$GIT_USER"

            # Switch to master and reset to current commit
            digest=$(git rev-parse HEAD)
            git checkout -b master 2>/dev/null || git checkout master
            git reset --hard $digest

            /tmp/workspace/release/dockmoor-linux_amd64 --asciidoc-usage > cmd/dockmoor/doc/dockmoor.adoc

            asciidoctor -b docbook5 cmd/dockmoor/doc/_readme.adoc
            pandoc -f docbook -t asciidoc --wrap=none --columns=120 cmd/dockmoor/doc/_readme.xml -o README.adoc

            VARS="$(cat cmd/dockmoor/doc/_vars.adoc)"
            BODY="$(cat README.adoc)"
            HEADER="$(cat cmd/dockmoor/doc/_header.adoc)"

            echo "$VARS
            :branch: master

            $HEADER

            $BODY
            " > README.adoc

            git add README.adoc
            # --allow-empty for rebuilds without release
            git commit --allow-empty -m ":gem: Release $tag"

            # Move tag
            git tag -fa "$tag" -m "Release $tag"
            git push --delete origin "$tag" || true
            git push --force-with-lease origin master --tags

            # Forward developer to master
            digest=$(git rev-parse HEAD)
            git checkout -b develop 2>/dev/null || git checkout develop
            git reset --hard $digest
            git push origin develop

      - run:
          name: Release new version
          command: |
            set -v
            tag=$CIRCLE_TAG

            ghr -t "$GITHUB_TOKEN" -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" --replace "$tag" /tmp/workspace/release/

  simulate_release:
    docker:
      - image: "$CI_PROJECT_PATH-builder:latest"
    working_directory: /go/src/github.com/MeneDev/dockmoor
    steps:
      - checkout
      - run:
          name: Check commit of generated content
          command: |
            set -v
            tag=$CIRCLE_TAG
            release_commit_msg="$(git log -1 --pretty=%B | head -n 1 || true)"
            if [ "$release_commit_msg" = ":gem: Release $tag" ]; then
              echo "This is a commit with generated content, skipping"
              circleci step halt
            fi

      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          key: gopkg-{{ checksum "Gopkg.lock" }}
          paths:
          - /go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/vendor
          - /tmp/go/cache
      - run:
          name: Download and build libraries
          command: |
            if [ ! -d ./vendor ]; then
                /go/bin/dep ensure
                find vendor/ -maxdepth 3 -mindepth 3 -exec bash -c 'cd $0 && go build  ./...' {} \;
            fi
      - save_cache:
          key: gopkg-{{ checksum "Gopkg.lock" }}
          paths:
          - ./vendor
          - /tmp/go/cache

      - run:
          name: End-to-End Test
          command: |
            cd cmd/dockmoor/end-to-end && ./test.sh

      - run:
          name: Update README.adoc
          command: |
            set -v
            tag=$CIRCLE_TAG

            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "$GIT_USER"

            # Switch to master and reset to current commit
            digest=$(git rev-parse HEAD)
            git checkout -b master 2>/dev/null || git checkout master
            git reset --hard $digest

            /tmp/workspace/release/dockmoor-linux_amd64 --asciidoc-usage > cmd/dockmoor/doc/dockmoor.adoc

            asciidoctor -b docbook5 cmd/dockmoor/doc/_readme.adoc
            pandoc -f docbook -t asciidoc --wrap=none --columns=120 cmd/dockmoor/doc/_readme.xml -o README.adoc

            VARS="$(cat cmd/dockmoor/doc/_vars.adoc)"
            BODY="$(cat README.adoc)"
            HEADER="$(cat cmd/dockmoor/doc/_header.adoc)"

            echo "$VARS
            :branch: master

            $HEADER

            $BODY
            " > README.adoc

            set +v
            echo "START README.adoc"
            cat README.adoc
            echo "END README.adoc"

            set -v

            git add README.adoc
            # --allow-empty for rebuilds without release
            git commit --allow-empty -m ":gem: Simulate Release"

            git push --force-with-lease --dry-run origin master --tags

            # Forward developer to master
            digest=$(git rev-parse HEAD)
            git checkout -b develop 2>/dev/null || git checkout develop
            git reset --hard $digest
            git push --dry-run origin develop


workflows:
  version: 2
  create_builder_and_release:
    jobs:
      - create_builder:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          requires:
              - create_builder
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - simulate_release:
          requires:
          - build
          filters:
            tags:
              ignore: /^v.*/
            branches:
              only: /.*/
      - release:
          requires:
              - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
